name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Run linting
      run: |
        uv run ruff check src/aadt/ tests/
        uv run ruff format --check src/aadt/ tests/

    - name: Run type checking
      run: |
        uv run ty src/aadt/

    - name: Run tests
      run: |
        uv run pytest tests/ -v --cov=aadt --cov-report=xml

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --group dev

    - name: Test package build
      run: |
        uv build
        uv run python -c "import aadt; print(f'AADT version: {aadt.__version__}')"

    - name: Test CLI
      run: |
        uv run aadt --help
        uv run aadt init test-project -y
        cd test-project
        uv run aadt ui
        uv run aadt clean